### ISSUE TITLE
yarn example.lec is failed

### ISSUE THREAD

**Issue by oioeic** [electron-lang/electron#37]
yyj@ubuntu:~/electron/examples/vdiv$ yarn
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
$ yarn build && yarn kicad && yarn bom
yarn run v1.12.3
$ lecc build
Done in 0.37s.
yarn run v1.12.3
$ lecc kicad VoltageDivider
src/voltagedivider.lec:12:22 - error: [kicad] Cell 'r1' is missing a pad assignment for port 'A'

12	  cell r1 = $R(10k) {A=vin, B=vout}
  
src/voltagedivider.lec:12:29 - error: [kicad] Cell 'r1' is missing a pad assignment for port 'B'

12	  cell r1 = $R(10k) {A=vin, B=vout}
  
src/voltagedivider.lec:18:22 - error: [kicad] Cell 'r2' is missing a pad assignment for port 'A'

18	  cell r2 = $R(22k) {A=vout, B=gnd}
  
src/voltagedivider.lec:18:30 - error: [kicad] Cell 'r2' is missing a pad assignment for port 'B'

18	  cell r2 = $R(22k) {A=vout, B=gnd}
  

Done in 0.45s.
yarn run v1.12.3
$ lecc bom VoltageDivider
Done in 0.36s.
Done in 2.42s.

**Comment by oioeic** [comment]
example.lec:

import $R from "@lec/electron/src/cells"

export module VoltageDivider {
  @left analog vin
  @right analog vout
  @bottom analog gnd

  @rotate(90)
  @value("10K")
  @footprint("Resistors_SMD:R_0402_NoSilk")
  @bom("Yageo", "RC0402FR-0710KL")
  cell r1 = $R(10k) {A=vin, B=vout}

  @rotate(90)
  @value("22K")
  @footprint("Resistors_SMD:R_0603_NoSilk")
  @bom("Yageo", "RC0603FR-0722KL")
  cell r2 = $R(22k) {A=vout, B=gnd}
}

**Comment by dvc94ch** [comment]
Depending on what you want, you have to  add attributes to the netlist.

Pretty schematic:
rotate + value
Kicad export:
footprint
Bom generation
bom

**Comment by dvc94ch** [comment]
Also check out the cpl attribute
https://electron-lang.org/docs/electron-reference.html#cpldescr

**Comment by dvc94ch** [comment]
I guess this issue can be closed. Feel free to reopen if you have any more questions
